Repository Barthol1/PHPEindopdracht, pull requests merged in 2022-05, with the labels that each got.

#14 Dusk tests pakketoverzicht, tracking, login, register
  PHPEindopdracht/app/Http/Controllers/DashboardController.php
  PHPEindopdracht/app/Imports/PackageImport.php
  PHPEindopdracht/composer.json
  PHPEindopdracht/composer.lock
  PHPEindopdracht/resources/views/dashboard.blade.php
  PHPEindopdracht/resources/views/tracing/index.blade.php
  PHPEindopdracht/tests/Browser/LoginTest.php
  PHPEindopdracht/tests/Browser/PackageOverviewTest.php
  PHPEindopdracht/tests/Browser/Pages/HomePage.php
  PHPEindopdracht/tests/Browser/Pages/Login.php
  PHPEindopdracht/tests/Browser/Pages/PackageOverview.php
  PHPEindopdracht/tests/Browser/Pages/Page.php
  PHPEindopdracht/tests/Browser/Pages/Register.php
  PHPEindopdracht/tests/Browser/Pages/Tracing.php
  PHPEindopdracht/tests/Browser/RegisterTest.php
  PHPEindopdracht/tests/Browser/TracingTest.php
  PHPEindopdracht/tests/Browser/console/.gitignore
  PHPEindopdracht/tests/Browser/screenshots/.gitignore
  PHPEindopdracht/tests/Browser/source/.gitignore
  PHPEindopdracht/tests/DuskTestCase.php
Labels: enhancement

#16 Feat/pakket pickup planning systeem
  PHPEindopdracht/app/Http/Controllers/API/PackageSignUpController.php
  PHPEindopdracht/app/Http/Controllers/AdminDashboardController.php
  PHPEindopdracht/app/Http/Controllers/DashboardController.php
  PHPEindopdracht/resources/views/admindashboard/index.blade.php
  PHPEindopdracht/resources/views/dashboard/index.blade.php
Labels: bug, enhancement

#17 Login en registratietests
  PHPEindopdracht/tests/Unit/LoginTest.php
Labels: enhancement

#18 Feat/unit tests
  PHPEindopdracht/app/Console/Commands/PackageCron.php
  PHPEindopdracht/app/Console/Kernel.php
  PHPEindopdracht/app/Http/Controllers/API/PackageSignUpController.php
  PHPEindopdracht/app/Rules/pickupDateTime.php
  PHPEindopdracht/tests/Browser/PackagePickUpTest.php
  PHPEindopdracht/tests/Browser/PackageSignUpTest.php
  PHPEindopdracht/tests/Browser/Pages/PackageOverview.php
  PHPEindopdracht/tests/Unit/PackagePickUpTest.php
  PHPEindopdracht/tests/Unit/PackageSignUpTest.php
Labels: enhancement

#19 Bug fix dusk tests
  PHPEindopdracht/app/Http/Controllers/AdminDashboardController.php
  PHPEindopdracht/app/Http/Controllers/DashboardController.php
  PHPEindopdracht/app/Http/Controllers/TracingController.php
  PHPEindopdracht/app/Imports/PackageImport.php
  PHPEindopdracht/database/factories/WebshopFactory.php
  PHPEindopdracht/resources/views/dashboard/index.blade.php
  PHPEindopdracht/tests/Browser/ClientWebshopTest.php
  PHPEindopdracht/tests/Browser/ExampleTest.php
  PHPEindopdracht/tests/Browser/PackageOverviewTest.php
  PHPEindopdracht/tests/Browser/PackagePickUpTest.php
  PHPEindopdracht/tests/Browser/PackageSignUpTest.php
  PHPEindopdracht/tests/Browser/Pages/PackageOverview.php
  PHPEindopdracht/tests/Browser/TracingTest.php
Labels: bug
